import { Segment } from "../types";

export const ZODIAC_SEGMENTS: Segment[] = [
    {
        id: "aries",
        name: "Овен",
        category: "Спорт и экстрим",
        status: "available",
        occupiedSlots: 3,
        totalSlots: 10,
        reach: 8500,
    },
    {
        id: "taurus",
        name: "Телец",
        category: "Дом и комфорт",
        status: "available",
        occupiedSlots: 7,
        totalSlots: 10,
        reach: 9200,
    },
    {
        id: "gemini",
        name: "Близнецы",
        category: "Технологии",
        status: "available",
        occupiedSlots: 5,
        totalSlots: 10,
        reach: 11000,
    },
    {
        id: "cancer",
        name: "Рак",
        category: "Семья и уют",
        status: "available",
        occupiedSlots: 8,
        totalSlots: 10,
        reach: 7800,
    },
    {
        id: "leo",
        name: "Лев",
        category: "Спорт и отдых",
        status: "available",
        occupiedSlots: 2,
        totalSlots: 10,
        reach: 12500,
    },
    {
        id: "virgo",
        name: "Дева",
        category: "Организация",
        status: "available",
        occupiedSlots: 6,
        totalSlots: 10,
        reach: 8900,
    },
    {
        id: "libra",
        name: "Весы",
        category: "Мода и стиль",
        status: "available",
        occupiedSlots: 9,
        totalSlots: 10,
        reach: 13200,
    },
    {
        id: "scorpio",
        name: "Скорпион",
        category: "Мистика",
        status: "full",
        occupiedSlots: 10,
        totalSlots: 10,
        reach: 9500,
    },
    {
        id: "sagittarius",
        name: "Стрелец",
        category: "Путешествия",
        status: "available",
        occupiedSlots: 4,
        totalSlots: 10,
        reach: 10800,
    },
    {
        id: "capricorn",
        name: "Козерог",
        category: "Бизнес",
        status: "available",
        occupiedSlots: 5,
        totalSlots: 10,
        reach: 11500,
    },
    {
        id: "aquarius",
        name: "Водолей",
        category: "Инновации",
        status: "available",
        occupiedSlots: 3,
        totalSlots: 10,
        reach: 14000,
    },
    {
        id: "pisces",
        name: "Рыбы",
        category: "Творчество",
        status: "available",
        occupiedSlots: 7,
        totalSlots: 10,
        reach: 8200,
    },
];

export const ACTION_NAME = "Гороскопные Скидки - Январь 2026";
